[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NITRO_PRESET = "netlify"

[functions]
  node_bundler = "none"
  directory = ".netlify/functions-internal"
